### ISSUE TITLE
Reporte de Architec

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-3-practica-architect-abicoronel#1]
[REPORTE DE PRACTICA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-abicoronel/files/9492124/REPORTE.DE.PRACTICA.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
